# Generated by Django 5.2 on 2025-05-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_mindApp', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
