# Generated by Django 5.2 on 2025-05-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_mindApp', '0003_remove_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
