# Generated by Django 5.2 on 2025-05-09 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_mindApp', '0004_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(max_length=20)),
                ('mood_rating', models.PositiveIntegerField()),
                ('thoughts', models.TextField()),
                ('reflection', models.TextField(blank=True)),
                ('gratitude', models.TextField(blank=True)),
                ('goal', models.CharField(blank=True, max_length=255)),
                ('self_care', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
